In [2]:
import pandas as pd
import numpy as np
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [4]:
df = pd.read_csv('tfidf_df.csv')
df.drop(df.columns[0], axis=1,inplace=True)
df

,aa,aaaaaaaaand,aap,aaron,aaronmacgruder,ab,ability,abortion,about,abraham,...,zipperhead,zoe,zog,zone,zoom,zzzzzz,num_tokens,mention_count,url_count,hashtag_count
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,14.0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2855,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0,0,0
2856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0,0
2857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,12.0,1,0,0
2858,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0,0,0
2859,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0,0,0

In [10]:
X = df.drop(columns = 'class')
Y = df['class']
# feature extraction
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, Y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[ 1.     1.     1.    ... 27.333  1.303  7.511]
[[0.41 0.   0.   0.  ]
 [0.1  0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.11 0.   0.   0.  ]
 [0.   0.   0.   0.  ]]

In [16]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', max_iter = 1000)
rfe = RFE(model, 5)
fit = rfe.fit(X, Y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

C:\Users\seanx\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=5 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)

Num Features: 5
Selected Features: [False False False ... False False False]
Feature Ranking: [2480 3311 3657 ... 2307 2914 1796]

In [32]:
cols = fit.get_support(indices=True)
features_df_new_LR = df.iloc[:,cols]
features_df_new_LR

      bitch  faggit  hockey  niggaz  pussies
0      0.41     0.0     0.0     0.0      0.0
1      0.10     0.0     0.0     0.0      0.0
2      0.00     0.0     0.0     0.0      0.0
3      0.11     0.0     0.0     0.0      0.0
4      0.00     0.0     0.0     0.0      0.0
...     ...     ...     ...     ...      ...
2855   0.20     0.0     0.0     0.0      0.0
2856   0.00     0.0     0.0     0.0      0.0
2857   0.00     0.0     0.0     0.0      0.0
2858   0.00     0.0     0.0     0.0      0.0
2859   0.13     0.0     0.0     0.0      0.0

[2860 rows x 5 columns]

In [35]:
from sklearn.ensemble import RandomForestClassifier


model2 = RandomForestClassifier()
rfe2 = RFE(model2, 100)
fit2 = rfe2.fit(X, Y)
print("Num Features: %d" % fit2.n_features_)
print("Selected Features: %s" % fit2.support_)
print("Feature Ranking: %s" % fit2.ranking_)

C:\Users\seanx\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=100 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)

Num Features: 100
Selected Features: [False False False ...  True  True  True]
Feature Ranking: [3955 3871 3851 ...    1    1    1]

In [37]:
cols2 = fit2.get_support(indices=True)
features_df_new_RF = df.iloc[:,cols2]
features_df_new_RF

,ain,all,ass,bad,be,bird,bitch,bitches,black,boy,...,wat,welfare,whistle,wishywashy,wolf,yh,zzzzzz,num_tokens,mention_count,url_count
0,0.0,0.00,0.0,0.0,0.00,0.0,0.41,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0
1,0.0,0.00,0.0,0.0,0.00,0.0,0.10,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0,0
2,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0,0
3,0.0,0.24,0.0,0.0,0.00,0.0,0.11,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0,0
4,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2855,0.0,0.00,0.0,0.0,0.00,0.0,0.20,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0,0
2856,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0
2857,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,1,0
2858,0.0,0.00,0.0,0.0,0.21,0.0,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0,0
2859,0.0,0.00,0.0,0.0,0.00,0.0,0.13,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0,0

In [38]:
rfe3 = RFE(model2, 250)
fit3 = rfe3.fit(X, Y)
print("Num Features: %d" % fit3.n_features_)
print("Selected Features: %s" % fit3.support_)
print("Feature Ranking: %s" % fit3.ranking_)
cols3 = fit3.get_support(indices=True)
features_df_new_RF2 = df.iloc[:,cols3]
features_df_new_RF2

C:\Users\seanx\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=250 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)

Num Features: 250
Selected Features: [False False False ...  True  True  True]
Feature Ranking: [4004 3963 3577 ...    1    1    1]

,account,af,ago,ain,all,always,america,another,around,ass,...,worthless,woulda,xxxtra,yeaaaaahhhh,yh,yost,zzzzzz,num_tokens,mention_count,url_count
0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0
1,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0,0
2,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0,0
3,0.0,0.0,0.0,0.0,0.24,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0,0
4,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2855,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0,0
2856,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0
2857,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,1,0
2858,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0,0
2859,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0,0